In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np

In [2]:
df = pd.read_csv("Netflix_Engagement_Report_2023_Jan-Jun_cleaned.csv", index_col=0)
df.head(15)

,Available Globally,Release Date,Hours Viewed
Title,,,
The Night Agent: Season 1,Yes,3/23/2023,812100000
Ginny & Georgia: Season 2,Yes,1/5/2023,665100000
The Glory: Season 1 // 더 글로리: 시즌 1,Yes,12/30/2022,622800000
Wednesday: Season 1,Yes,11/23/2022,507700000
Queen Charlotte: A Bridgerton Story,Yes,5/4/2023,503000000
You: Season 4,Yes,2/9/2023,440600000
La Reina del Sur: Season 3,No,12/30/2022,429600000
Outer Banks: Season 3,Yes,2/23/2023,402500000
Ginny & Georgia: Season 1,Yes,2/24/2021,302100000
FUBAR: Season 1,Yes,5/25/2023,266200000
Manifest: Season 4,Yes,11/4/2022,262600000
Kaleidoscope: Limited Series,Yes,1/1/2023,252500000
Firefly Lane: Season 2,Yes,12/2/2022,251500000
The Mother,Yes,5/12/2023,249900000
Physical: 100: Season 1 // 피지컬: 100: 시즌 1,Yes,1/24/2023,235000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18214 entries, The Night Agent: Season 1 to 선생 김봉두
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Available Globally  18214 non-null  object
 1   Release Date        4855 non-null   object
 2   Hours Viewed        18214 non-null  int64
dtypes: int64(1), object(2)
memory usage: 569.2+ KB

In [4]:
df.describe()

       Hours Viewed
count  1.821400e+04
mean   5.130954e+06
std    1.871767e+07
min    1.000000e+05
25%    2.000000e+05
50%    7.000000e+05
75%    3.400000e+06
max    8.121000e+08

In [5]:
duplicados = df[df.duplicated(keep='first')]
print(duplicados)

                                   Available Globally Release Date  \
Title
Peppa Pig: Season 2                                No          NaN
New Amsterdam (2018): Season 4                     No          NaN
The Walking Dead: Season 9                         No          NaN
Rosario Tijeras (Mexico): Season 1                 No          NaN
Teen Titans Go!: Season 5                          No          NaN
...                                               ...          ...
راس السنة                                          No          NaN
心が叫びたがってるんだ。                                       No          NaN
두근두근 내 인생                                          No          NaN
라디오 스타                                             No          NaN
선생 김봉두                                             No          NaN

                                    Hours Viewed
Title
Peppa Pig: Season 2                     63700000
New Amsterdam (2018): Season 4          57500000
The Walking Dead: Season 9              51200000
Rosario Tijeras (Mexico): Season 1      48500000
Teen Titans Go!: Season 5               48100000
...                                          ...
راس السنة                                 100000
心が叫びたがってるんだ。                              100000
두근두근 내 인생                                 100000
라디오 스타                                    100000
선생 김봉두                                    100000

[12823 rows x 3 columns]

In [6]:
df.drop_duplicates(keep='first', inplace=True)

In [7]:
df.head(30)

,Available Globally,Release Date,Hours Viewed
Title,,,
The Night Agent: Season 1,Yes,3/23/2023,812100000
Ginny & Georgia: Season 2,Yes,1/5/2023,665100000
The Glory: Season 1 // 더 글로리: 시즌 1,Yes,12/30/2022,622800000
Wednesday: Season 1,Yes,11/23/2022,507700000
Queen Charlotte: A Bridgerton Story,Yes,5/4/2023,503000000
You: Season 4,Yes,2/9/2023,440600000
La Reina del Sur: Season 3,No,12/30/2022,429600000
Outer Banks: Season 3,Yes,2/23/2023,402500000
Ginny & Georgia: Season 1,Yes,2/24/2021,302100000
FUBAR: Season 1,Yes,5/25/2023,266200000
Manifest: Season 4,Yes,11/4/2022,262600000
Kaleidoscope: Limited Series,Yes,1/1/2023,252500000
Firefly Lane: Season 2,Yes,12/2/2022,251500000
The Mother,Yes,5/12/2023,249900000
Physical: 100: Season 1 // 피지컬: 100: 시즌 1,Yes,1/24/2023,235000000
Crash Course in Romance: Limited Series // 일타 스캔들: 리미티드 시리즈,Yes,1/14/2023,234800000
Love Is Blind: Season 4,Yes,3/24/2023,229700000
BEEF: Season 1,Yes,4/6/2023,221100000
The Diplomat: Season 1,Yes,4/20/2023,214100000
Luther: The Fallen Sun,Yes,3/10/2023,209700000
Fake Profile: Season 1 // Perfil falso: Temporada 1,No,5/31/2023,206500000
Vikings: Valhalla: Season 2,Yes,1/12/2023,205500000
Extraction 2,Yes,6/16/2023,201800000
"XO, Kitty: Season 1",Yes,5/18/2023,200700000
Doctor Cha: Limited Series // 닥터 차정숙: 리미티드 시리즈,Yes,4/15/2023,194700000
Shadow and Bone: Season 2,Yes,3/16/2023,192900000
Outer Banks: Season 1,Yes,4/15/2020,184000000
Sweet Tooth: Season 2,Yes,4/27/2023,182300000
You People,Yes,1/27/2023,181800000
Perfect Match: Season 1,Yes,2/14/2023,176800000

In [8]:
df.dropna(inplace=True) # excluir as linhas com dados faltantes

In [9]:
date = df[df['Release Date'].str.contains('4/11/2023')] # filtrando registro
print(date)

                               Available Globally Release Date  Hours Viewed
Title
Leanne Morgan: I'm Every Woman                 No    4/11/2023       6700000